config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :comments
  resources :sub_tasks
  resources :tasks
  resources :projects
  resources :phases
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    authenticated :user do
      root to: 'home#index'
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/sub_task.rb
class SubTask < ApplicationRecord
    belongs_to :task
end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController
  before_action :set_sub_task, only: %i[ show edit update destroy ]

  # GET /sub_tasks or /sub_tasks.json
  def index
    @sub_tasks = SubTask.all
  end

  # GET /sub_tasks/1 or /sub_tasks/1.json
  def show
  end

  # GET /sub_tasks/new
  def new
    @sub_task = SubTask.new
    @task_id = params["id"]
    url = request.original_url

    @new = url.include? "new"
  end

  # GET /sub_tasks/1/edit
  def edit
  end

  # POST /sub_tasks or /sub_tasks.json
  def create
    @sub_task = SubTask.new(sub_task_params)
    
    

    respond_to do |format|
      if @sub_task.save
        format.html { redirect_to project_url(:id => @sub_task.task.project_id), notice: "Sub task was successfully created." }
        format.json { render :show, status: :created, location: @sub_task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sub_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_tasks/1 or /sub_tasks/1.json
  def update
    respond_to do |format|
      if @sub_task.update(sub_task_params)
        format.html { redirect_to sub_task_url(@sub_task), notice: "Sub task was successfully updated." }
        format.json { render :show, status: :ok, location: @sub_task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sub_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_tasks/1 or /sub_tasks/1.json
  def destroy
    @sub_task.destroy

    respond_to do |format|
      format.html { redirect_to sub_tasks_url, notice: "Sub task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_task
      @sub_task = SubTask.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sub_task_params
      params.require(:sub_task).permit(:title, :status,:task_id)
    end
end

app/helpers/sub_tasks_helper.rb
module SubTasksHelper
end

app/views/sub_tasks/_form.html.erb
<%= form_with(model: sub_task) do |form| %>
  <% if sub_task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sub_task.errors.count, "error") %> prohibited this sub_task from being saved:</h2>

      <ul>
        <% sub_task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title,placeholder:"title",style:"width:100%" %>
  </div>

  <div class="mb-2">
    <%= form.label :status, style: "display: block;width:100%" %>
    <%= form.collection_select :status,Phase.all,:title,:title, style:"width:100%; height:60px" %>
  </div>
  <div class="mb-3">
        <%if @new==true%>
        <%= form.hidden_field :task_id,value:@task_id %>
        <%else%>
        <%= form.hidden_field :task_id,value:@sub_task.task_id %>
        <%end%>
      </div>
    <div>
    <button type="submit" class="btn btn-info w-100">
    <% if @new==true %>
      <%="Create "%>
    <%else%>
      <%="Update "%>
      <%end%>
       Sub Task</button>
  </div>
<% end %>

app/views/sub_tasks/_sub_task.html.erb
<div id="<%= dom_id sub_task %>">
  <p>
    <strong>Title:</strong>
    <%= sub_task.title %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= sub_task.status %>
  </p>

</div>

app/views/sub_tasks/edit.html.erb
<div class="mx-auto mt-5 pt-5 login d-flex flex-column justify-content-center align-items-center" 
style="width: 550px; height: 650px; background:linear-gradient(90deg, rgba(238, 130, 238, 1) 0%, rgba(0, 0, 255, 1) 100%);">
  <div class="bg-white p-5">

    <h1 class="text-info">Editing sub task</h1>

    <%= render "form", sub_task: @sub_task %>

    <div class="pt-2">
      <%= link_to "Back to task", url_for(:back)%>
    </div>
  </div>
</div>

app/views/sub_tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sub tasks</h1>

<div id="sub_tasks">
  <% @sub_tasks.each do |sub_task| %>
    <%= render sub_task %>
    <p>
      <%= link_to "Show this sub task", sub_task %>
    </p>
  <% end %>
</div>

<%= link_to "New sub task", new_sub_task_path %>

app/views/sub_tasks/new.html.erb
<div class="mx-auto mt-5 pt-5 login d-flex flex-column justify-content-center align-items-center" 
style="width: 550px; height: 650px; background:linear-gradient(90deg, rgba(238, 130, 238, 1) 0%, rgba(0, 0, 255, 1) 100%);">
  <div class="bg-white p-5">
    <h1 class="text-info" >New sub task</h1>

    <%= render "form", sub_task: @sub_task %>

    <div class="d-flex align-items-center justify-content-center pt-2">
      <%= link_to "Back to Task", url_for(:back) %>
    </div>
  </div>
</div>

app/views/sub_tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sub_task %>

<div>
  <%= link_to "Edit this sub task", edit_sub_task_path(@sub_task) %> |
  <%= link_to "Back to sub tasks", sub_tasks_path %>

  <%= button_to "Destroy this sub task", @sub_task, method: :delete %>
</div>