config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :comments
  resources :sub_tasks
  resources :tasks
  resources :projects
  resources :phases
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    authenticated :user do
      root to: 'home#index'
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
    has_many_attached :files

    belongs_to :task
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: %i[ show edit update destroy ]

  # GET /attachments or /attachments.json
  def index
    @attachments = Attachment.all
    @tasks = Task.all
  end

  # GET /attachments/1 or /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments or /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to attachment_url(@attachment), notice: "Attachment was successfully created." }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1 or /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to attachment_url(@attachment), notice: "Attachment was successfully updated." }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1 or /attachments/1.json
  def destroy
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to attachments_url, notice: "Attachment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attachment_params
      params.require(:attachment).permit(:task_id,:files =>[])
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_attachment.html.erb
<div id="<%= dom_id attachment %>">
<%if attachment.files.attached?%>
    <div>
    <% attachment.files.each do |file| %>
        <%if file.image?%>
            <%= image_tag(file, :width => 200) %>
        <% elsif file.video? %>
             <%= video_tag(url_for(file), :width => 200,controls: "" )%>
        <% elsif file.audio? %>
             <%= audio_tag(url_for(file), :width => 200,controls: "" )%>
        <% else%>
             <%= link_to file.filename, url_for(file), :width => 200 %>
        <%end%>
    <% end %>
    </div>
<%end%>
</div>

app/views/attachments/_form.html.erb
<%= form_with(model: attachment) do |form| %>
  <% if attachment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
        <% attachment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="files">
  <%= form.label :task %>
  <%= form.collection_select :task_id, Task.all, :id , :id%>
</div>

<div class="files">
  <%= form.label :files %>
  <%= form.file_field :files, :multiple => true %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render "form", attachment: @attachment %>

<br>

<div>
  <%= link_to "Show this attachment", @attachment %> |
  <%= link_to "Back to attachments", attachments_path %>
</div>

app/views/attachments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attachments</h1>

<div id="attachments">
  <% @attachments.each do |attachment| %>
    <%= render attachment %>
    <p>
      <%= link_to "Show this attachment", attachment %>
    </p>
  <% end %>
</div>

<%= link_to "New attachment", new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render "form", attachment: @attachment %>

<br>

<div>
  <%= link_to "Back to attachments", attachments_path %>
</div>

app/views/attachments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attachment %>

<div>
  <%= link_to "Edit this attachment", edit_attachment_path(@attachment) %> |
  <%= link_to "Back to attachments", attachments_path %>

  <%= button_to "Destroy this attachment", @attachment, method: :delete %>
</div>