config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :comments
  resources :sub_tasks
  resources :tasks
  resources :projects
  resources :phases
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    authenticated :user do
      root to: 'home#index'
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    belongs_to :phase
    has_many :tasks
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
    @value =10
  end

  # GET /projects/1 or /projects/1.json
  def show
    @value =10
    @project_some = @project
    @new_count =0
    @inprogress_count =0
    @completed_count = 0
    @comment = Comment.new 

    
  end

  # GET /projects/new
  def new
    @project = Project.new
    url = request.original_url
    myArray = url.split('/')
    @new = myArray.last == 'new'
  end

  # GET /projects/1/edit
  def edit
    url = request.original_url
    myArray = url.split('/')
    @edit = myArray.last == 'edit'
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @phas
    Phase.all.each do |phase|
      if phase.title == @project.status
        @phas = phase
      end
    end
    @project.phase =@phas

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :status, :due_date)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title ,placeholder:"Enter Title"%>
  </div>

  <div class="mb-3">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description,placeholder:"Enter description" %>
  </div>

  <div class="mb-3">
    <%= form.label :status, style: "display: block" %>
    <%= form.collection_select :status, Phase.all, :title, :title %>
  </div>

  <div class="mb-3">
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div class="mb-3 d-flex align-items-center justify-content-between" >
    <div >
          <%if @new==true%>
          <%= link_to "Back", root_url%>
          <%else%>
          <%=link_to "Back", project_url(:id=>project.id)%>
          <%end%>
    </div>
    <button type="submit" class="btn btn-primary">
    <%if @edit==true%> 
    <%="Update "%>
    <%else%>
    <%="Create "%>
    <%end%>
    project
    </button>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="container" id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= project.status %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= project.due_date %>
  </p>

</div>

app/views/projects/edit.html.erb
<div class="mx-auto mt-5 pt-5 login d-flex flex-column justify-content-center align-items-center" 
style="width: 550px; height: 650px;background:linear-gradient(90deg, rgba(238, 130, 238, 1) 0%, rgba(0, 0, 255, 1) 100%);">
  <div class="bg-white p-5">
<div class="d-flex flex-column mt-4 justify-content-center align-items-center" >
<h1 class="text-info">Editing project</h1>
<%= render "form", project: @project %>

</div>
</div>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<div class="mx-auto mt-5 pt-5 login d-flex flex-column justify-content-center align-items-center" 
style="width: 550px; height: 650px; background:linear-gradient(90deg, rgba(238, 130, 238, 1) 0%, rgba(0, 0, 255, 1) 100%);">
  <div class="bg-white p-5">
    <div class="d-flex flex-column mt-4 justify-content-center align-items-center" >
    <h1 class="text-info">New project</h1>

    <%= render "form", project: @project %>

    </div>
    </div>
</div>

app/views/projects/show.html.erb
<div class="m-5 col">
  <div class="d-flex justify-content-between">
    <div class="d-flex">
      <span ><h5><%= @project.title%></h5></span>
      <span>
        <a class="text-decoration-none" href="<%= edit_project_url(:id=>@project.id) %>">
          <i class="bi bi-pen-fill m-3"></i>
          </a>
          </span>
    </div>
    <div>
      <a class="text-decoration-none" href="<%= root_url %>">
        <i class="bi bi-arrow-left text-dark"></i>
      </a>
    </div>
  </div>
  <hr class="bg-secondary border-2 border-top border-secondary">
  <div class="d-flex justify-content-between m-4">
    <div class="border border-info border-bottom-0 text-info p-1">Task List</div>
    <div class="text-clr">Audit Report</div>
    <div>Upload Task</div>
    <div>Task Report</div>
    <div>User Report</div>
    <div>Notification</div>
    <div>Access Rights</div>
    <div>Category Order</div>
  </div>
  <div class="text-decoration-none">
    <a class="text-decoration-none" href="<%= new_task_path(:id =>@project.id) %>">
          <span class="text-align-center border text-weight-bold p-1 rounded text-info" style="color: #63C5DA">+ Add a Task</span>
    </a>
  </div>
  <div class="row">
    <%Phase.all.each do |phase|%>
      <%if phase.title!="OnHold"%>
       <div class="col bg-light m-2  shadow-sm">
          <h6 class="font-weight-bold"><%if phase.title == "New"%>
            <%="Todo"%>
          <%else%>
            <%=phase.title%>
          <%end%> 
          <%=" (#{@value} )"%>
           </h6>
          <div>
          <%Task.all.each do |task|%>
            <% if task.status == phase.title && task.project_id == @project.id%>
            <div  class="shadow-sm border-info border col p-3 bg-white m-3 rounded">
              <div class="d-flex justify-content-end">
                
                <span>
                   <a class="text-decoration-none text-dark" href="<%= edit_task_url(:id=>task.id) %>">
                    <i class="bi bi-pen-fill m-1"></i>
                  </a>
                </span>

                <span>
                   
                  <i class="bi bi-trash-fill m-1"></i>
                </span>

                <span><i class="bi bi-list font-weight-bolder"></i></span>
                
              </div>
              <div>                      
              <p class="fs-5"><i class="bi bi-circle-fill" style="color : yellow"></i><%=" #{task.title} "%><i class="bi bi-hourglass-top"></i></p>
              <p class="ps-4"><%=task.description%>
              <p class=" fs-6"><i class="bi bi-person-fill text-info fs-5 pe-1" style="color: #63C5DA"></i> <%= " #{task.select_member}" %></p>
              <%if phase.title=="Completed"%>
              <p class="ps-1" ><i class="bi bi-calendar-week-fill text-danger pe-2"></i>
              <%if task.end_date%>
                <%=task.end_date%>
              <%else%>
                <%= Time.now.strftime("%Y-%m-%d") %>
              <%end%>
              </p>
              <%end%>
              <div class="p-1 border border-warning">
                  <h6 class="text-warning p-2 pb-1">Sub Tasks</h6>
                  <div >
                    <%SubTask.all.each do |subtask|%>
                      <% if subtask.task_id == task.id%>
                        <div class=" p-3 m-2 border border-danger">
                          <%= subtask.title%>
                        </div>
                      <%end%>
                    <%end%>

                  </div>
              </div>

              </div>

              <div class="text-decoration-none pt-3">
                <a class="text-decoration-none" href="<%= new_sub_task_path(:id =>task.id) %>">
                      <span class="text-align-center border text-weight-bold p-1 rounded text-info" style="color: #63C5DA">Add a SubTask</span>
                </a>
              </div>
              <div class="p-2" >
                <h6 id="comment_" style="cursor:pointer">Comments</h6>

                <div class="p-2 " style="display:block; text-decoration:none" id="comments_" >
                    <%Comment.all.each do |comment|%>
                      <%if comment.task_id == task.id%>
                        <h6><%=comment.user.fullname%></h6>
                        <p><%=comment.body%></p>
                      <%end%>
                    <%end%>
                </div>

                
                 <%= form_for @comment, :html => {:class => 'home-form without-entry clearfix'}  do |f| %>
                      <%= f.text_field :body, placeholder: 'Enter your comments'%>
                      <%= f.hidden_field :task_id , value:task.id%>
                      <%= f.hidden_field :user_id, value:current_user.id%>
                      <button type="submit"><i class="bi bi-send-fill"></i></button>
                  <% end %>
              </div>
            </div>
              
            <%end%>
          <%end%>
          
        </div>
        </div>
        
      <%end%>
    <%end%>
  <div>

  
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#comment_').click(function(){
      $('#comments_').toggle()
    })
    $('#comment_').hover(function(){
       $(this).css("text-decoration", "underline");
    },function(){
        $(this).css("text-decoration", "none");
    }
    )
  })

  $("#form_submit").submit(function(){

  })

  setTimeout(function() {
    $('#successMessage').fadeOut('fast');
  }, 1500); 
</script>
<%if notice%>
<p style="color: green; width:300px; left:40%; top:10%" class="position-absolute  alert alert-success border  " id="successMessage"><%= notice %> </p>
<%end%>